# This is a basic workflow to help you get started with Actions

name: Page Generator

# 代码 push 到 master 分支的时候运行该 workflow
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # node 打包生成静态文件
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: fasle # false 是用 personal token，true 是使用 GitHub token
          fetch-depth: 0 # 保证能够 push 成功

      # Runs a single command using the runners shell
      - name: Install Node
        uses: actions/setup-node@v1
      
      - name: Install Yarn
        run: |
          pwd
          npm install yarn -g
      
      - name: Install Node Dependencies
        run: |
          pwd
          yarn install
      
      - name: Install SubPackage
        run: |
          pwd
          bin/pm install
      
      - name: Website Install Node Dependencies
        run: |
          pwd
          npm i
        working-directory: ./website
     
      - name: Build Page
        run: |
          pwd
          make
        working-directory: ./website
      
      - name: Add Message
        working-directory: ./website/public
        run: |
          pwd
          echo "prosemirror.xheldon.com" > CNAME
          echo -e "# [ProseMirror Chinese doc](https://prosemirror.xheldon.com) \n\nGenerated by [https://github.com/xheldon-prosemirror/prosemirror](https://github.com/xheldon-prosemirror/prosemirror) " > README.md
     
      - name: Commit and Push
        working-directory: ./website/public
        run: |
          pwd
          git init
          git checkout -b gh
          git add -A
          git -c user.name='github actions by ${{github.actor}}' -c user.email='NO' commit -m 'update docs' 
          git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" HEAD:gh -f -q
